### ISSUE TITLE
make it work with pypy3

### ISSUE THREAD

**Issue by unhammer** [goavki/streamparser#3]
pypy3 makes it 3x faster (which is very handy when using it for testvoc over millions of lines of input), but doesn't have Enum at all, and doesn't allow changing the namedtuple.**doc** (for SReading).

**Comment by sushain97** [comment]
Looks like you did this already? Does the latest version of PyPy3 support Enums yet? The subclassing code makes me a tad bit sad.

**Comment by unhammer** [comment]
Yeah, I think we can close this. It is sad, but then those enums aren't very amazing either … I'd prefer wide compatibility since this library is at its most useful when we can expect it to run on the computer of any language dev doing testvoc/training etc.
