### ISSUE TITLE
Add license headers

### ISSUE THREAD

**Issue by ghost** [goavki/streamparser#7]
@unhammer and @sushain97: decide upon the license as discussed in irc and add the license headers.

**Comment by sushain97** [comment]
I'm not really a fan of adding large license headers. However, I am okay with switching

    __license__ = "GPLv3"

to

    __license__ = "GPLv3+"

**Comment by ghost** [comment]
You're missing the warranty clause (well, was it in the full license file?) and could GPLv3+ be understood ambiguously? I think so. Also how will people know what copyright stuff they need to put in their code when they use bit and bytes from this repo?

**Comment by ghost** [comment]
Ah, well, the author/copyright part was in the python data field.

**Comment by unhammer** [comment]
>  the warranty clause (well, was it in the full license file?) 

It is.

> could GPLv3+ be understood ambiguously

That looks unambiguous to me, and is how it's used e.g. here: https://pypi.python.org/pypi?%3Aaction=search&term=gplv3%2B&submit=search

> how will people know what copyright stuff they need to put in their code when they use bit and bytes from this repo

There's one source file, and one LICENSE file.

**Comment by ghost** [comment]
What about the people who don't know yet what GPLv3+ means? They would be then missing out the option to use also the later version as they could only think it is GPLv3 (as they only see the LICENSE file). Also, all the pypi pages that I checked had also the full license header there (in the pypi page) and their source code, e.g. https://github.com/i3visio/cardify/blob/master/scripts/cardify_launcher.py had it, too. @sushain97 I don't see how 15 lines of text in the source file would be so bad. Hmm, or maybe you could add it to the README, that wouldn't mess the source code, right?

**Comment by sushain97** [comment]
Adding the lines to the source code isn't really bad but it feels
unnecessary to me especially given that GPLv3 == GPLv3+ until a new version
has been released.

**Comment by ghost** [comment]
GPLv3 != GPLv3+ – other people than the original authors might think their new projects (forked etc. from this) future, too and then it is important to know whether the license is GPLv3 or GPLv3+.

**Comment by unhammer** [comment]
If Someone Else forks it and claims it is GPLv3-only and a Third Party notices, then the Third Party can complain to that Someone Else who was too lazy to ask or google what "GPLv3+" means.

**Comment by ghost** [comment]
Okay, do how you want :)

**Comment by ghost** [comment]
@unhammer , @sushain97: would one of you do the change (as you seemed to have agreed upon)?
