### ISSUE TITLE
parse doesn't accept strings

### ISSUE THREAD

**Issue by ghost** [goavki/streamparser#8]
The given example in the readme doesn't work with current version. See this paste from @nuboro: 

```
from streamparser import parse
lexicalUnits = parse('^hypercholesterolemia/*hypercholesterolemia$\[\]\^\$[^ignoreme/yesreally$]^a\/s/a\/s<n><nt>$^vino/vino<n><m><sg>/venir<vblex><ifi><p3><sg>$.eefe^dímelo/decir<vblex><imp><p2><sg>+me<prn><enc><p1><mf><sg>+lo<prn><enc><p3><nt>/decir<vblex><imp><p2><sg>+me<prn><enc><p1><mf><sg>+lo<prn><enc><p3><m><sg>$')
for lexicalUnit in lexicalUnits:
    print('%s (%s) → %s' % (lexicalUnit.wordform, lexicalUnit.knownness, lexicalUnit.readings))


====================================================================================

    textBuffer += next(stream)
TypeError: 'str' object is not an iterator
```

**Comment by unhammer** [comment]
So a workaround is prepending a `c for c in ` there:

`parse(c for c in '^hypercholesterolemia/*hypercholesterolemia$\[\]\^\$[^ignoreme/yesreally$]^a\/s/a\/s<n><nt>$^vino/vino<n><m><sg>/venir<vblex><ifi><p3><sg>$.eefe^dímelo/decir<vblex><imp><p2><sg>+me<prn><enc><p1><mf><sg>+lo<prn><enc><p3><nt>/decir<vblex><imp><p2><sg>+me<prn><enc><p1><mf><sg>+lo<prn><enc><p3><m><sg>$')`

But perhaps we should have a wrapper for non-iterables to make it a bit easier to use? 

One could also do a dispatch based on type; I personally don't like that very much, but I don't really know what's the most pythonic solution.

**Comment by ghost** [comment]
"dispatching" based on type could be done with try-except solution, which is not bad.

**Comment by sushain97** [comment]
single-dispatch ftw
